server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    enabled: true
  security:
    user:
      name: herbertt
      password: 123456
      roles: admin

